# Generated by Django 5.2.3 on 2025-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_duration_alter_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=12, help_text='Duración en semanas'),
        ),
    ]
